### ISSUE TITLE
Is there any bug with this driver

### ISSUE THREAD

**Issue by macsupermac** [ChefKissInc/NootRX#1]
Congratulations！！！Navi 22 has already work in Hackintosh！！！I have the same question as before.

**Comment by VisualEhrmanntraut** [comment]
Nope, no observable bugs so far

**Comment by VisualEhrmanntraut** [comment]
You're welcome, from me and ExtremeXT.

**Comment by macsupermac** [comment]
> You're welcome, from me and ExtremeXT.
I have a question,When will Iris Xe receive support？

**Comment by VisualEhrmanntraut** [comment]
Never!!!!

**Comment by macsupermac** [comment]
> Never!!!! :-D

I will conduct a test tomorrow and provide feedback on the issue at that time

**Comment by jinitaimei12345678** [comment]
这真是令人震撼

**Comment by L1keava** [comment]
> Nope, no observable bugs so far

glad to hear this good news ，will this kext support RDNA for laptops?

**Comment by VisualEhrmanntraut** [comment]
@L1keava no
