### ISSUE TITLE
nuc8i7hvk issue

### ISSUE THREAD

**Issue by ivan-ef** [ChefKissInc/NootRX#10]
nuc8i7hvk i7-8809G with integrated Radeon RX Vega M GH
whatevergreen and polaris22fixup kexts was disabled

no GPU installed yet

got this error 

![tempImageB2wL59](https://github.com/ChefKissInc/NootRX/assets/67600440/8eff9b1d-333f-4d59-bd1d-6811570f6124)

**Comment by VisualEhrmanntraut** [comment]
Vega M is Polaris, not RDNA.

**Comment by ivan-ef** [comment]
I want to use RX6700XT with external EGPU box

**Comment by VisualEhrmanntraut** [comment]
What do you expect to happen if the GPU is not plugged in anyway? In any case, this panic is not related to the kext. This is user error.

**Comment by ivan-ef** [comment]
> What do you expect to happen if the GPU is not plugged in anyway? In any case, this panic is not related to the kext. This is user error.

So does it theoretically possible to use both gpu?

Without nootrx kext it does boot correct.

**Comment by ExtremeXT** [comment]
@ivan-ef Well, does your Thunderbolt even work?

**Comment by ivan-ef** [comment]
> @ivan-ef Well, does your Thunderbolt even work?

Yes, it does work. The tb controller was flashed with custom firmware. 
Tested egpu with vega 56
