### ISSUE TITLE
Blender metal not working with RX 6700 XT

### ISSUE THREAD

**Issue by ayush179959** [ChefKissInc/NootRX#102]
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 3600X

### What is your GPU's model?

AMD Radeon RX 6700 XT

### Please describe the behaviour in detail.

I installed blender and I opened it, then I went to preference -> system and then selected metal but it says no metal supported GPU's available
I am using blender 4.3 and noot rx release version (also tried it with debug version)
I tried Geekbench and it detects my RX 6700 XT with metal and the benchmark did ran with the GPU ( I could see my gpu fans moving faster during the benchmark) 

Here are some screenshots that might help

![Image](https://github.com/user-attachments/assets/85c5078b-977e-4741-9d94-3252b4758a3f)
![Image](https://github.com/user-attachments/assets/19d38982-4ca5-448f-b280-3ebed77d2fca)
![Image](https://github.com/user-attachments/assets/77ab25dc-cb46-4c56-9835-e2aba485bf81)

### What should've happened instead?

Blender should be able to use metal api through nootRX using my RX 6700 XT

**Comment by VisualEhrmanntraut** [comment]
this is a blender issue, read the text: "requires apple silicon".
