### ISSUE TITLE
Youtube can't play 4k video

### ISSUE THREAD

**Issue by PikeDown** [ChefKissInc/NootRX#15]
### macOS Version

Sonoma

### What is your CPU's model?

i5 10400

### What is your GPU's model?

XFX 6750XT

### Please describe the behaviour in detail.

YouTube keeps loading but wont play when switching to 2k/4k resolution
apple music wont play either

### What should've happened instead?

video playing normally

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Timed out waiting for response.
