### ISSUE TITLE
AMD R7 6800H iGPU 680M 

### ISSUE THREAD

**Issue by lsmir3** [ChefKissInc/NootRX#16]
### macOS Version

Monterey

### What is your CPU's model?

AMD R7 6800H

### What is your GPU's model?

RX680m

### Please describe the feature in detail.

AMD R7 6800H It's a mobile processor, will NootRX drive his IGPU correctly? I've recently made plans to purchase it, will it be able to drive him into the system. This is my current concern. I'd appreciate an answer. I posted a stupid reply yesterday that caused my account to fail to create ISSUES, so I've created a new account and would like to be relieved of my duties under account number 21307369.

### What alternatives have you tried, if any?

Haven't started trying yet

### Feature request submission terms

- [ ] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [ ] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [ ] The feature being present in NootRX makes sense.
- [ ] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by ExtremeXT** [comment]
@lsmir3 No support for iGPUs.
