### ISSUE TITLE
Can't boot to the installer on 6750 XT

### ISSUE THREAD

**Issue by mx4address** [ChefKissInc/NootRX#20]
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 7 3800X

### What is your GPU's model?

AMD Radeon RX 6750 XT

### Please describe the behaviour in detail.

When trying to boot the installer the monitor turns on and off and won't boot to the setup screen (Apple logo is also not showing)

### What should've happened instead?

The setup screen should show up.

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Womp womp

**Comment by mx4address** [comment]
?

**Comment by mx4address** [comment]
@VisualEhrmanntraut can you explain

**Comment by ExtremeXT** [comment]
@mx4address What EXACT macOS version are you on?

**Comment by mx4address** [comment]
> @mx4address Where is the installer image fetched from?

I'm using the online method, the com.apple.recovery.boot image

**Comment by mx4address** [comment]
is that the problem? also my GPU is an MSI Radeon RX 6750 XT Gaming X Trio, and my board is a B450 AORUS ELITE

**Comment by VisualEhrmanntraut** [comment]
these projects are not the only things we have to spend our time on
anyway, can you show your kexts

**Comment by mx4address** [comment]
![image](https://github.com/ChefKissInc/NootRX/assets/84406344/52c7517e-8e27-4460-9869-391b20eba9e0)
I tried many boot-args just in case, I tried some other things but it either black screened with the issue I stated or IOG flags 0x3 pops up and it won't boot.

**Comment by mx4address** [comment]
(note that if you want my EFI I'll provide it)

**Comment by VisualEhrmanntraut** [comment]
Is your BIOS up to date? And is Legacy Boot/CSM turned off?

**Comment by mx4address** [comment]
I tried two BIOS versions, F61 and F65e, and yes, CSM is disabled. But nothing worked.

**Comment by mx4address** [comment]
Is this an issue with my GPU by the way, or is my hardware conflicting?

**Comment by VisualEhrmanntraut** [comment]
Idk just going through standard troubleshooting steps. For now you can try getting macOS installed without NootRX (just disable the kext, no need to add something like WEG) and then reenabling it and see if it works there

**Comment by mx4address** [comment]
isn't whatevergreen required on opencore's guide?

**Comment by VisualEhrmanntraut** [comment]
Does nothing for unsupported GPUs

**Comment by mx4address** [comment]
alright. I'll test this out later

**Comment by mx4address** [comment]
@VisualEhrmanntraut it just says "Generation from SMC report as 2" and it won't let me go further.

**Comment by VisualEhrmanntraut** [comment]
@mx4address Then it's a configuration issue.

**Comment by mx4address** [comment]
what does that mean?

**Comment by VisualEhrmanntraut** [comment]
It means the problem is not NootRX.

**Comment by mx4address** [comment]
I honestly have no idea, I had a GTX 1060 and it worked with OpenCore and High Sierra previously.

**Comment by mx4address** [comment]
it's possible the GPU is really not supported

**Comment by mx4address** [comment]
oops accidentally closed.

**Comment by VisualEhrmanntraut** [comment]
No even if it was unsupported you'd still get a signal

**Comment by VisualEhrmanntraut** [comment]
> The bug only happens with NootRX enabled.

Welp, considering you signed the above term without it being true, this issue will be closed. Join our Telegram group for support.
