### ISSUE TITLE
Colors are wrong on 6750 XT + graphical glitches.

### ISSUE THREAD

**Issue by mx4address** [ChefKissInc/NootRX#21]
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 7 3800X

### What is your GPU's model?

AMD Radeon RX 6750 XT

### Please describe the behaviour in detail.

The colors are wrong on my monitor and there are graphical glitches when moving windows around.

### What should've happened instead?

Colors should be right with no graphical glitches.

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by mx4address** [comment]
Yes I finally got the GPU to work.

**Comment by VisualEhrmanntraut** [comment]
Very nice description with many very clear pictures of the problem. Will be fixing it ASAP!

**Comment by mx4address** [comment]
I am also using DisplayPort by the way.
