### ISSUE TITLE
Google Chrome does not have VP9/AV1 hardware decoding

### ISSUE THREAD

**Issue by Mutcholoko** [ChefKissInc/NootRX#24]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 7 5700G

### What is your GPU's model?

AMD Radeon RX 6750 XT

### Please describe the behaviour in detail.

Although hardware acceleration is working, it only supports hardware decoding and only H264 and HEVC. I'd also like to point out that hardware encoding is not working on Chrome, but working on other apps such as OBS Studio.
![image](https://github.com/ChefKissInc/NootRX/assets/46263572/c60d5d59-6165-4d9e-ae91-22231bfdb266)

### What should've happened instead?

VP9 and AV1 should show up on the list. Hardware encoding should also show H264 and HEVC.

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
@Mutcholoko I don't think macOS' dGPU drivers support either of those, only the Intel iGPU ones.

**Comment by Mutcholoko** [comment]
That seems to be the case then. I was comparing with my Hackintosh laptop, which indeed has an Intel iGPU. I'm closing this issue.

**Comment by Mutcholoko** [comment]
@VisualEhrmanntraut I know the issue is closed, but do you have any info on whether or not Safari supports VP9 hardware decoding and/or any sort of hardware encoding on an AMD GPU? I could't find any info on that online.
