### ISSUE TITLE
install MacOS with NootRX - nothing will work

### ISSUE THREAD

**Issue by maksimlenskii** [ChefKissInc/NootRX#33]
### macOS Version

Ventura

### What is your CPU's model?

i9 14900KF

### What is your GPU's model?

RX6750GRE

### Please describe the behaviour in detail.

An important point for those who want to install MacOS with NootRX - nothing will work. The slider gets stuck at the last moment after a reboot, when the splash screen with the choice of language should appear and the slider does not move. Rebooting from EFI without NootRX or with WEG helps. This applies to both Ventura and Sonoma. But the initial boot, working with the disk and the first two stages of installation are successful,

### What should've happened instead?

MacOS installation is successful

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Acidanthera/bugtracker#2286

**Comment by VisualEhrmanntraut** [comment]
(I interpreted it as “Installing macOS with NootRX will get stuck on the slider at the last moment before the Out Of Box Experience”)
