### ISSUE TITLE
get temperature stats?

### ISSUE THREAD

**Issue by DatreRSX** [ChefKissInc/NootRX#35]
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 5600X

### What is your GPU's model?

AMD RX 6700 XT (Navi 22)

### Please describe the feature in detail.

Get temperature sensor work

### What alternatives have you tried, if any?

radeon temperature kext

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
That's not in the goals of this project. If you are encountering an issue with our RadeonSensor kext (ChefKissInc/RadeonSensor), report it there.
