### ISSUE TITLE
Is the Navi 33 have a chance to happen this year?

### ISSUE THREAD

**Issue by kyvaith** [ChefKissInc/NootRX#37]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 5 5600G

### What is your GPU's model?

AMD Radeon RX 7600 XT

### Please describe the feature in detail.

The "soon™" is cool, but I wonder what are the predictions for the next chips. Should I replace my Nvidia RTX 2080 with RX 7600 XT hoping it will be supported later this year, or stick with Ryzen's 5 5600G Vega 7 with NootedRed.

### What alternatives have you tried, if any?

I use AMD Ryzen's 5 5600G Vega 7 iGPU with NootedRed.

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
The README says Navi 24. RDNA 3 is not supported in macOS.

**Comment by kyvaith** [comment]
Ahh clear, so it's a limitation od macOS not the driver itself. Too bad.

**Comment by VisualEhrmanntraut** [comment]
Although I must add that it could be possible to edit the RDNA 2 drivers a bit to turn it into RDNA 3, considering it looks like RDNA 3 is just RDNA 2 with some extra instructions and some other stuff. But just like Navi 24, the code for its DCN version must be patched into AMDRadeonX6000Framebuffer. This all is a lot of work, and I am the only dev, so, yeah.
