### ISSUE TITLE
Fail Update MacOs Ventura with the Noot kext

### ISSUE THREAD

**Issue by maksimlenskii** [ChefKissInc/NootRX#39]
### macOS Version

Ventura

### What is your CPU's model?

14900KF

### What is your GPU's model?

RX 6750 GRE

### Please describe the behaviour in detail.

Has anyone already updated MacOs Ventura with the Noot kext? This is the second time I have stopped after the update in the middle of the bar. The first time after finishing the installation of MacOs Ventura itself, at the last stage before the language selection screen appears. That time I just used the old bootloader without NootRX, but WEG was there. This time after the Ventura update the same thing - I had to use the old bootloader after the update to get through the last stage of the update.

### What should've happened instead?

The update should proceed without interruption

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Acidanthera/bugtracker#2286
