### ISSUE TITLE
Please support RX 6750 GRE 10G

### ISSUE THREAD

**Issue by ton-im** [ChefKissInc/NootRX#40]
### macOS Version

Ventura

### What is your CPU's model?

Intel i7 10700

### What is your GPU's model?

AMD Radeon RX 6750 GRE 10G

### Please describe the feature in detail.

I want NootRX to be able to support RX 6750 GRE 10G.
I seek the Model.cpp , 6750 GRE 's ID is 73DF 0xE5 , but it is one of IDs .
AMD Radeon RX 6750 GRE 12G 's ID are 73DF 0xE5 and 73DF 0xD5 .
AMD Radeon RX 6750 GRE 10G 's ID is 73FF 0xDF .
All these ID 's devices are Navi22 .

### What alternatives have you tried, if any?

I fork my own copy of NootRX , replace 73DF to 73FF , replace 73FF to 73DF , use Actions compling .
It do not work on my RX 6750 GRE 10G.

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
The model is just cosmetic. This GPU is already supported. If you are encountering issues, you will have to be more specific than "it doesn't work".

**Comment by ton-im** [comment]
When I use rx6750gre10g , enable NootRX and disable WEG in Kernel to install Ventura , the screen is red .
After install end , the first start : when opencore's progress bar(or code by -v) over , the screen is no signel .
All of them same as I disable NootRX and WEG .
So I think my card do not be identified .

**Comment by ton-im** [comment]
Beacuse of RX 6750 GRE 10G 's ID is 73FF , same as Navi23 .
I seek the code , find none to process this ID as Navi22 .
But I found "
case 0x73FF:
chipType = ChipType::Navi23;
"

**Comment by ton-im** [comment]
This deviceId is in /System/Library/Extensions/AMDRadeonX6000.kext.
(just guess)macOS do not process revision , macOS think this card is a Navi23 card .

**Comment by ton-im** [comment]
This deviceId is in /System/Library/Extensions/AMDRadeonX6000.kext.
(just guess)macOS do not process revision , macOS think this card is a Navi23 card .

**Comment by VisualEhrmanntraut** [comment]
<img width="771" alt="Screenshot 2024-03-26 at 22 20 44" src="https://github.com/ChefKissInc/NootRX/assets/30368284/df951a85-cbb7-41ac-9936-73da7c010155">
Looks like you're right. Why did they do this?

**Comment by VisualEhrmanntraut** [comment]
[NootRX-1.0.0-RELEASE.zip](https://github.com/ChefKissInc/NootRX/files/14764303/NootRX-1.0.0-RELEASE.zip)

@ton-im tell me if this works

**Comment by ton-im** [comment]
It works great on Ventura 13.6.5 and Sonoma 14.3 .
Thank you . @VisualEhrmanntraut

**Comment by maksimlenskii** [comment]
RX6750GRE - nice work on Ventura today, but still waiting DRM support )
