### ISSUE TITLE
6750 GRE 12G System is shown as AMD Radeon RX 6000 Series

### ISSUE THREAD

**Issue by lsmir3** [ChefKissInc/NootRX#42]
### macOS Version

Sonoma

### What is your CPU's model?

intel 8400

### What is your GPU's model?

AMD Radeon RX 6750 GRE 12G

### Please describe the behaviour in detail.

![Snipaste_2024-03-30_18-48-52](https://github.com/ChefKissInc/NootRX/assets/152374006/506dcb28-f666-4dbe-b17a-571b5a4cf0f6)
![Snipaste_2024-03-30_18-56-41](https://github.com/ChefKissInc/NootRX/assets/152374006/ac636a9d-dcfd-4e85-83cc-2a81820b155d)

### What should've happened instead?

NO

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by lsmir3** [comment]
Hardware decoding failed .I see that someone 6700 xt hard decoding is normal.
![Snipaste_2024-03-31_22-59-19](https://github.com/ChefKissInc/NootRX/assets/152374006/5fbea971-252c-4742-bf0b-cad139572400)


![Snipaste_2024-03-31_23-37-25](https://github.com/ChefKissInc/NootRX/assets/152374006/91c39c0d-2ec7-4fdc-883d-d0c029ef0ea2)

**Comment by VisualEhrmanntraut** [comment]
Wrong SMBIOS, kext conflict, ...
