### ISSUE TITLE
Low performance with AMD CPU?

### ISSUE THREAD

**Issue by nighv0120** [ChefKissInc/NootRX#44]
### macOS Version

Sonoma

### What is your CPU's model?

AMD R5 5600x

### What is your GPU's model?

AMD RX 6700xt

### Please describe the feature in detail.

I have an RX6700xt GPU and R5 5600x CPU, after using RootRX.kext, the GPU (opencl) score of Geekbech 6 is 3w+, my friend's computer is configured with GPU RX6700xt and CPU 12600kf, and his Geekbecn 6 score is 7w-8w+, can this be solved?

### What alternatives have you tried, if any?

I've tried using the same system version and OC bootstrapping

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
He might have an overclocked version of the GPU, like a Nitro card.

**Comment by nighv0120** [comment]
> 他可能有一个超频版本的GPU，比如硝基卡。

I'm sure he doesn't have an overclocked version of the GPU, the difference between me and his computer configuration is the CPU and motherboard, maybe AMD's CPU and motherboard are the cause of the low GPU performance?

**Comment by VisualEhrmanntraut** [comment]
Oh. @nighv0120 switch the PAT patch to Shaneee's; disable the first to last one, enable the last one. (Kernel > Patch)

**Comment by nighv0120** [comment]
> 哦。@nighv0120将 PAT 补丁切换为 Shaneee 的；禁用第一个到最后一个，启用最后一个。 （内核 > 补丁）

no effect

**Comment by VisualEhrmanntraut** [comment]
That's not possible.

**Comment by nighv0120** [comment]
> That's not possible.

![1434954001](https://github.com/ChefKissInc/NootRX/assets/75463973/04ff127b-69eb-41f4-a650-9a51345c37ed)
![JVAFFE{(QR3T3HEHXO9 I69](https://github.com/ChefKissInc/NootRX/assets/75463973/a462a261-119e-4d81-99da-a4dd6fc6b339)

**Comment by VisualEhrmanntraut** [comment]
You enabled them both, instead of disabling one and enabling the other.

**Comment by nighv0120** [comment]
> That's not possible.

This one is my friend's, and he uses an Intel CPU
![Image_1712646093368](https://github.com/ChefKissInc/NootRX/assets/75463973/99c2bbdf-2154-4a05-bc4c-ac778790b749)
![Uploading Image_1712646066591.png…]()

**Comment by VisualEhrmanntraut** [comment]
I am going to block you from the organisation if you continue failing to follow my directions.

**Comment by nighv0120** [comment]
> That's not possible.

This is my friend, who uses Intel's CPU
![Image_1712646093368](https://github.com/ChefKissInc/NootRX/assets/75463973/ef0ccfea-0946-490e-8999-947b5b0a7097)
![Image_1712646066591](https://github.com/ChefKissInc/NootRX/assets/75463973/a833af41-8d2e-49a7-a831-ce5f94881ca9)

**Comment by nighv0120** [comment]
> I am going to block you from the organisation if you continue failing to follow my directions.

Well, what do you say I should do

**Comment by VisualEhrmanntraut** [comment]
I already told you; you enabled both of the patches instead of what I actually told you to do.

**Comment by nighv0120** [comment]
> 我已经告诉过你;您启用了这两个补丁，而不是我实际上告诉您要做的事情。

Do you only enable Shaneee patches and disable all other patches?

**Comment by VisualEhrmanntraut** [comment]
@nighv0120 我告诉过你启用 "Shaneee "补丁（最后一个），禁用 "algrey "补丁（Shaneee 补丁之前的那个）。

Hopefully that's an adequate translation for you.

**Comment by nighv0120** [comment]
> @nighv0120 我告诉过你启用 Shaneee 补丁（最后一个），禁用 Algrey 补丁（Shaneee 补丁之前的那个）。
> 
> Hopefully that's an adequate translation for you.

Thank you for your patient reply, because of the language barrier, I don't understand the advice you provided, I will try again the advice you provided, thank you

**Comment by nighv0120** [comment]
> @nighv0120 我告诉过你启用 Shaneee 补丁（最后一个），禁用 Algrey 补丁（Shaneee 补丁之前的那个）。
> 
> Hopefully that's an adequate translation for you.

Thank you so much for helping me, it's so important to me
![28738187](https://github.com/ChefKissInc/NootRX/assets/75463973/a134253b-82a4-4223-8faa-198b06d810bd)
![2834618070](https://github.com/ChefKissInc/NootRX/assets/75463973/0ed7f603-e030-47e6-9ec9-b8e27497db81)
