### ISSUE TITLE
Add support for AMD Radeon (TM) R5 M330

### ISSUE THREAD

**Issue by Sayor00** [ChefKissInc/NootRX#47]
### macOS Version

Sonoma

### What is your CPU's model?

Intel(R) Core(TM) i3-5005U

### What is your GPU's model?

AMD Radeon (TM) R5 M330

### Please describe the feature in detail.

I want it to support AMD Radeon (TM) R5 M330 GPU

### What alternatives have you tried, if any?

Nothing

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
that's GCN 1.......
