### ISSUE TITLE
Sonoma 14.4.1 dont boot  post install 

### ISSUE THREAD

**Issue by DatreRSX** [ChefKissInc/NootRX#48]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 5 5600X

### What is your GPU's model?

AMD Radeon RX 6700XT

### Please describe the behaviour in detail.

When i installed the lastest sonoma 14.4.1 the post install first boot never boot , the kernel reboot at this line :
"apfs_stop_bg_work:875 : System is shutting down - stop any bg work " , use whatevergrre with nootrx disable at first post install  boot can be fix the problem?

### What should've happened instead?

Normal boot 

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
1. Our kexts cannot be used during Installation or Upgrade due to a Lilu bug causing a stall at the last phase
2. This is unrelated to the kext. This is a bug with OpenCore, you need to set SecureBootModel to Disabled
