### ISSUE TITLE
Can it support Radeon RX 6950 XT

### ISSUE THREAD

**Issue by luoweihz** [ChefKissInc/NootRX#49]
### macOS Version

Sonoma

### What is your CPU's model?

i7 13700KF

### What is your GPU's model?

Radeon RX 6950 XT

### Please describe the feature in detail.

I want NootRX can support Radeon RX 6950 XT

### What alternatives have you tried, if any?

no

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
That's Navi 21, it should already be supported either natively by macOS or added by the kext. What is the issue exactly? And also provide me with the device ID of the card.

**Comment by luoweihz** [comment]
thanks for your support,RX 6950 XT indeed was supported,you can close this ticket.

best regards
