### ISSUE TITLE
Screens just turn off with NootRX on Ventura and Sonoma in a Rosetta Cryptex Install/Environment

### ISSUE THREAD

**Issue by herrnst** [ChefKissInc/NootRX#5]
**Describe the bug**

On macOS Monterey (updated to 12.7), with NootRX my RX6700XT works just wonderful (during boot, the screen turns off for about 10 seconds and then both monitors turn on with fully working acceleration).

On both Ventura and Sonoma (which need to be installed with CryptexFixup in place), when NootRX is enabled, the screen turns off and it seems nothing is happening any more (monitors don't turn on and generally the system appears dead). Without NootRX, the system starts as expected but obiously runs sluggish and the second monitor isn't working.

This is on a SandyBridge i7-2600+16GB RAM (thus the reason for CryptexFixup).

**To Reproduce**
1. Prepare install media, prepare OC config with the usual board ID skip patches and boot with "-no_compat_check", install
2. Install NootRX into EFI/OC/Kexts, enable in OC's config.plist, boot
3. Depending on using "-v" or not, the progress bar advanced to about 1/3 (or verbose messages scroll by), screen turns off, system appears dead

**Expected behavior**
Boot to the login screen with both monitors displaying a picture and have working acceleration (just as with Monterey).

**System Information:**
 - CPU: Intel Core i7-2600 w/16GB RAM on an Asus P8Z77V-LX
 - GPU: AMD Radeon RX 6700 XT w/12GB (Asus branded)
 - macOS Versions: Monterey 12.7 (working fine), both Ventura 13.6 and Sonoma 14.0 non-working

**Additional context**
For any testing, I'm keeping a 13.6 install around.

I'm not really sure on how to obtain any useful information or verbose output esp. about what really happens when the system dies, but can and will do if I receive according instructions.

Footnote: Thank you all very much for bringing such life to officially unsupported hardware!

**Comment by VisualEhrmanntraut** [comment]
AMD kexts need AVX2 in Ventura and newer. You might be able to bypass this by using OCLP, which downgrades a lot of macOS' binaries and kexts. This configuration however is not supported by us, and you're on your own. Sorry. Good luck.

**Comment by herrnst** [comment]
I see, this is the thing with AVX2 then. I somehow was under the impression that this also is an issue with Monterey as well, and as it just worked after dropping in NootRX and getting issues in Ventura+, I thought that doing the Cryptex thing would also take care of any drivers and frameworks, AND accelerated graphics sort-of worked in the installer environment, so...

OCLP seem to be no dice, since as it reads they didn't get Navi to work (yet) using root-patching and downgrading Kexts and Frameworks.

Ohwell, might aswell just be about time to put the good old 2600 to rest after 12 1/2 years...

That said, again thank you guys very much for all your efforts!

**Comment by VisualEhrmanntraut** [comment]
@herrnst All Cryptex is just dyld. So the kext is just forcing use of the Rosetta dyld. So everything else is still untouched.
