### ISSUE TITLE
Stuck at installation due to Lilu bug

### ISSUE THREAD

**Issue by scanduz** [ChefKissInc/NootRX#50]
### macOS Version

Sonoma

### What is your CPU's model?

Mac Pro 5.1

### What is your GPU's model?

Asus rog strix rx 6650 xt

### Please describe the feature in detail.

Hi, my name is Angelo, thanks to your kext I managed to get my rx 6650 xt working on a real mac pro 5.1 with mac os monterey. Then I tried to update to Sonoma, but the loading for the initialization phase i.e. the last phase stops before the halfway point. Is there a solution to this problem? Thanks in advance

### What alternatives have you tried, if any?

I tried entering the startup argument but the problem persists

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Acidanthera/bugtracker#2286
