### ISSUE TITLE
No Signal Past Userspace Handoff | RESOLVED

### ISSUE THREAD

**Issue by pmnlla** [ChefKissInc/NootRX#57]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 7 5800X3D

### What is your GPU's model?

AMD Radeon RX 6700 XT Reference

### Please describe the behaviour in detail.

Continuation of #55. It would be better to document it here rather than as a discussion.

When using NootRX and booting MacOS Sonoma 14.4.1, after the kernel's verbose logging, the GPU outputs no signal. This occurs no matter what input is used, DP or HDMI.

My config.plist is attached. Please note that, as of now, I am using whatevergreen and swapping GPUs to an RX 580 whenever I need to use MacOS. **However, I do not use NootRX and whatevergreen at the same time. This is known to cause problems** There are no other changes to the EFI. If it's required to rebuild and retest with NootRX, let me know.

Steps I've done to attempt to remedy the situation:
- Add `adgpmod=pikera` to boot-args. This doesn't exist in NootRX, but it's worth trying.
- Add `adgpmod-ignore` to boot-args. Dotrania guide referenced.
- Attempted different display outputs, both HDMI and DVI.
- Used an older version of lilu.
[config.zip](https://github.com/ChefKissInc/NootRX/files/15378491/config.zip)

### What should've happened instead?

MacOS should be booting past the kernel-userspace handoff, and displaying the login interface.

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
rip

**Comment by pmnlla** [comment]
fym rip 💀

**Comment by hg13bs** [comment]
@pmnlla I don't think you need this section in your DeviceProperties fr

<dict>
    <key>framebuffer-con0-type = 00080000</key>
    <data>AAgAAA==</data>
    <key>framebuffer-con2-type = 00080000</key>
    <string>00080000</string>
    <key>framebuffer-con1-type = 00080000</key>
    <string>00080000</string>
   </dict>

**Comment by pmnlla** [comment]
That got it! Thanks @hg13bs! But now my card is detected as a Navi 23 card and I don't have hardware accel. 
Victorious About This Mac prompt attached.

![Screenshot 2024-05-20 at 1 16 38 PM](https://github.com/ChefKissInc/NootRX/assets/39027165/beef979d-c7fa-47db-ab33-7d3422ddbacb)

**Comment by hg13bs** [comment]
@pmnlla do you have NootRX kext? and remove WhateverGreen.kext if still there

**Comment by VisualEhrmanntraut** [comment]
@pmnlla this config does not have NootRX but WhateverGreen instead in it
<img width="1552" alt="Screenshot 2024-05-20 at 20 19 20" src="https://github.com/ChefKissInc/NootRX/assets/30368284/2f0c03e7-f86d-4e03-b72e-1f03c152ff02">

**Comment by pmnlla** [comment]
[config (2).zip](https://github.com/ChefKissInc/NootRX/files/15380059/config.2.zip)
@VisualEhrmanntraut @hg13bs Here's the config with nootRX.

**Comment by VisualEhrmanntraut** [comment]
@pmnlla are you sure ALL your kexts are up to date

**Comment by pmnlla** [comment]
I'm fairly sure the kexts are up to date.
![image](https://github.com/ChefKissInc/NootRX/assets/39027165/93f11cbb-94fd-4cd3-89a7-32c885a3d8b2)

**Comment by VisualEhrmanntraut** [comment]
WhateverName.app isn't a kext. Also, I suggest you remove AMDRCPUPM and SMCAMDP because they cause issues with clock speeds amongst other things, see https://chefkissinc.github.io/guide/guide-differences#amdryzencpupowermanagement-and-smcamdprocessor.

**Comment by pmnlla** [comment]
WhateverName is there so I remember where it was and don't go looking for it hysterically once I have usb stuff set up. AMDCPUPM and SMCAMDP are removed now. Will reboot and test.

**Comment by VisualEhrmanntraut** [comment]
WhateverName is not useful for us, you can just throw it to the bin.

**Comment by pmnlla** [comment]
Yup, it's gone. Regardless, acceleration still isn't here. Should I try the adgpmod flags again?

**Comment by hg13bs** [comment]
@pmnlla lol those flags don't exist in NootRX per what Visual said

**Comment by VisualEhrmanntraut** [comment]
No, as I've mentioned in prior discussions this boot argument does not exist in NootRX as I strive for a Drag&Drop experience. Can you tell me which device ID your card has? I don't think anyone has tested a reference card with the kext.

**Comment by pmnlla** [comment]
That's what I was thinking. But I'm desperate enough to try them again. IIRC NootRX automatically deals with that graphics stuff, whereas WhateverGreen required these flags be explicitly specified.

**Comment by pmnlla** [comment]
> No, as I've mentioned in prior discussions this boot argument does not exist in NootRX as I strive for a Drag&Drop experience. Can you tell me which device ID your card has? I don't think anyone has tested a reference card with the kext.

Yep. Can I do it through macOS with Hackintool?

**Comment by VisualEhrmanntraut** [comment]
Maybe?

**Comment by pmnlla** [comment]
Worth a shot. Worst case scenario I'll do it through Windows.

**Comment by VisualEhrmanntraut** [comment]
You can always look at the IOKit registry, either with Apple's IORegistryExplorer, IOBrowser or the built-in ioreg tool

**Comment by pmnlla** [comment]
`PCI\VEN_1002&DEV_73DF&SUBSYS_0E361002&REV_C1` - what Windows Device Manager gave me under Hardware IDs. What else should I search for?

**Comment by VisualEhrmanntraut** [comment]
0x73DF is indeed the Navi 22 device ID. Don't see why your acceleration doesn't work, in that case.

**Comment by VisualEhrmanntraut** [comment]
Hmm... how about you disable AppleALC and AirportItlwm just as a test?

**Comment by pmnlla** [comment]
Let's give that a shot.

**Comment by pmnlla** [comment]
Nada. Still no acceleration. Let me try to boot to the Ventura installer to see if that one works. I don't recall many breaking changes between Ventura and Sonoma though.

**Comment by VisualEhrmanntraut** [comment]
The installer has no graphical acceleration, that's Apple's design choice. Let's try an older version of NootRX instead.

**Comment by VisualEhrmanntraut** [comment]
@pmnlla try this build https://github.com/ChefKissInc/NootRX/actions/runs/8771044723/artifacts/1432956986

**Comment by pmnlla** [comment]
Will do. What build are you thinking?

**Comment by pmnlla** [comment]
Didn't help. Tried an nvram reset on the way too.

**Comment by VisualEhrmanntraut** [comment]
Okay, let's go another commit behind: https://github.com/ChefKissInc/NootRX/actions/runs/8490422295/artifacts/1371441675

**Comment by pmnlla** [comment]
Nada. Do you mind unbanning me from the telegram chat, so we can go through this troubleshooting while keeping this issue clean? I personally don't mind documenting it here but I figured I'd ask regardless.

My gut feeling is that there's some kind of fallback occurring that's forcing use of an integrated GPU which doesn't exist. But I haven't seen anyone reference that as an occurrence in macOS.

**Comment by VisualEhrmanntraut** [comment]
nah that's not happening. Is your motherboard's firmware up to date? Did you disable CSM/Legacy Boot?

**Comment by pmnlla** [comment]
Fair enough. Mobo firmware is up to date, and CSM is disabled. I do have a custom driver installed to force rebar on Turing cards, but I doubt that's interfering here.

**Comment by VisualEhrmanntraut** [comment]
RBAR? If you have that enabled in the motherboard's settings, macOS does not play well with that at all.

**Comment by pmnlla** [comment]
RBAR is disabled, actually. I used to have it enabled, then disabled it because I doubt I need it as of now. Don't I need a specific boot flag to tell macOS it's disabled enough?

**Comment by VisualEhrmanntraut** [comment]
Above 4G Decoding is not Resizable BAR, although enabling the former can enable the latter. Also, `npci` cannot be used with Above 4G and if you have Resizable BAR enabled you need to set `ResizeAppleGpuBars` to `0`

**Comment by pmnlla** [comment]
Above 4G doesn't appear in my bios settings, although RBAR does. RBAR is disabled. I'm guessing it means Above 4G is disabled too?

**Comment by VisualEhrmanntraut** [comment]
That likely means it's force enabled, so you should try without the `npci` boot arg.

**Comment by pmnlla** [comment]
Frozen on PCIe Configuration Begin.

**Comment by VisualEhrmanntraut** [comment]
Try in addition enabling ReBAR and setting `ResizeAppleGpuBars` to `0`

**Comment by pmnlla** [comment]
Was just about to. Will report with results.

**Comment by pmnlla** [comment]
Zilch.

**Comment by VisualEhrmanntraut** [comment]
🤷🏼‍♂️ the only next troubleshooting steps I have in mind now is to debug the driver, however I am too tired for that, maybe tomorrow. Maybe @hg13bs or someone else watching has any ideas.

**Comment by pmnlla** [comment]
All good. Will have a look at the amd-osx discord. Let me know if you wanna debug it anytime soon.

**Comment by pmnlla** [comment]
Came up with an idea. since macOS seems to be incorrectly detecting my card, should I try to spoof it to another PCIe ID? maybe 73ce?

**Comment by pmnlla** [comment]
Rude 💀
