### ISSUE TITLE
About RX 550 Lexa

### ISSUE THREAD

**Issue by TahsinFaiyaz30** [ChefKissInc/NootRX#58]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 5 3600

### What is your GPU's model?

AMD Radeon RX 550 Lexa

### Please describe the feature in detail.

This is not a request but I just want to know how can I use the RX 550 Lexa in macOS Sonoma? WHat kext will I need? whateverGreen? or any patching?

### What alternatives have you tried, if any?

This is not a request but I just want to know how can I use the RX 550 Lexa in macOS Sonoma? WHat kext will I need? whateverGreen? or any patching?

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by hg13bs** [comment]
@TahsinFaiyaz30 RX 5500 is natively supported, you can use either NootRX or WhateverGreen if you need DRM

**Comment by TahsinFaiyaz30** [comment]
> @TahsinFaiyaz30 RX 5500 is natively supported, you can use either NootRX or WhateverGreen if you need DRM

No no it it RX 550 Lexa, not 5500.

**Comment by hg13bs** [comment]
@TahsinFaiyaz30 then just use WhateverGreen

**Comment by TahsinFaiyaz30** [comment]
> @TahsinFaiyaz30 then just use WhateverGreen

any patches?

**Comment by VisualEhrmanntraut** [comment]
@TahsinFaiyaz30 I apologise on behalf of my friend’s misconception. This GPU you have just needs a device ID spoof to the non-Lexa variant.

**Comment by TahsinFaiyaz30** [comment]
> @TahsinFaiyaz30 I apologise on behalf of my friend’s misconception. This GPU you have just needs a device ID spoof to the non-Lexa variant.

Can you give me a tutorial link?

**Comment by VisualEhrmanntraut** [comment]
`DeviceProperties` > `Add` > `PciRoot(…) path of GPU` `Dict` > `device-id` `Data` <`ff670000`>

**Comment by TahsinFaiyaz30** [comment]
> `DeviceProperties` > `Add` > `PciRoot(…) path of GPU` `Dict` > `device-id` `Data` <`ff670000`>

Only adding this will word? and whatever green? no SSDT spoof needed? Amd my device id is 0x699f

**Comment by hg13bs** [comment]
@TahsinFaiyaz30 doing this should be enough, don't need SSDT to spoof

**Comment by hg13bs** [comment]
additionally you must get the PciRoot path from Windows or in macOS with gfxutil

**Comment by TahsinFaiyaz30** [comment]
> additionally you must get the PciRoot path from Windows or in macOS with gfxutil

Okkk thanks a lot. I will try

**Comment by TahsinFaiyaz30** [comment]
@VisualEhrmanntraut , I also want to say something. I have two more ids, but I cant make a issue or anything with those ids. it says I cant comment. My those IDs are Sayor0630 and Sayor00. Can you see what happened. I cant do anything to any of your repos. But in others repos, i can do everything.

**Comment by VisualEhrmanntraut** [comment]
<img width="189" alt="Screenshot 2024-05-23 at 21 04 07" src="https://github.com/ChefKissInc/NootRX/assets/30368284/886d3cf5-980b-472c-a00c-ca1cc601115f">

**Comment by VisualEhrmanntraut** [comment]
show what you did

**Comment by TahsinFaiyaz30** [comment]
> show what you did

![CleanShot 2024-05-24 at 00 47 45](https://github.com/ChefKissInc/NootRX/assets/167909751/88e7c675-80d8-49fc-a1ad-89b331782193)

**Comment by VisualEhrmanntraut** [comment]
fuck me sideways it's a gosh darn configurator user. should've expected it when you revealed your true identity. shoo!
