### ISSUE TITLE
6750GRE unavailable

### ISSUE THREAD

**Issue by yutianhot** [ChefKissInc/NootRX#6]
**Expected behavior**
Unable to drive on AMD 6750GRE
https://www.amd.com/en/products/graphics/amd-radeon-rx-6750-gre-12gb

**System Information:**
 - macOS Version: macOS 13.5.1
 - CPU: Intel 14700KF
 - GPU: AMD 6750GRE 12G

**Additional context**
https://pic2.58cdn.com.cn/nowater/webim/big/n_v22c0b96e498f14a9f8895b23188bc360a.jpg

**Comment by ExtremeXT** [comment]
What device ID does this GPU have?

**Comment by yutianhot** [comment]
https://pic5.58cdn.com.cn/nowater/webim/big/n_v2b83131df951242e88a10ef30c25583b9.jpg

**Comment by ExtremeXT** [comment]
> https://pic5.58cdn.com.cn/nowater/webim/big/n_v2b83131df951242e88a10ef30c25583b9.jpg

Access to pic5.58cdn.com.cn was deniedYou don't have authorization to view this page.
HTTP ERROR 403

**Comment by yutianhot** [comment]
https://i.ibb.co/7zks4Jn/1698035689875.jpg

**Comment by ExtremeXT** [comment]
> https://i.ibb.co/7zks4Jn/1698035689875.jpg

No device ID there. If you have Windows, go to Device Manager -> Display Adapters -> RX 6750 GRE -> Details -> Hardware IDs and paste the first string here.

**Comment by yutianhot** [comment]
Okay, I'll install a Windows app and see what the driver ID is.  thank you

**Comment by VisualEhrmanntraut** [comment]
<img width="82" alt="Screenshot 2023-10-23 at 09 38 53" src="https://github.com/ChefKissInc/NootRX/assets/30368284/e60922d4-bf83-4675-81d5-6a3dabc80fec">
@yutianhot This card is supported. Please provide more information about the issue.

**Comment by yutianhot** [comment]
Hello, I have resolved the issue by reinstalling MacOS and it has been confirmed that NootRX supports AMD 6750GRE.

https://i.ibb.co/pdhqG5P/image.png

I have used a friend's modified NootRX to display the specific model of the graphics card.



thank you

**Comment by VisualEhrmanntraut** [comment]
@yutianhot your model name has been added
