### ISSUE TITLE
Macos 15 sequoia can't drive 6700xt

### ISSUE THREAD

**Issue by Love-Myself-Song** [ChefKissInc/NootRX#64]
### macOS Version

Sonoma

### What is your CPU's model?

intel i9 7940X

### What is your GPU's model?

AMD RX6700XT

### Please describe the behaviour in detail.

It can be used normally in sonoma. After upgrading to sequoia, it can't be driven. I saw that the latest version has added support for sequoia, but in fact it can't be driven. At least my graphics card is like this.

### What should've happened instead?

It should have been driven normally.

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by Love-Myself-Song** [comment]
macos 15 sequoia 确实是新发布的beta测试版系统  是需要到正式版本发布后才会更新支持么?

**Comment by zss66** [comment]
我的也是无法支持 @Love-Myself-Song ，如果有解决的方法，请告知我一下

**Comment by VisualEhrmanntraut** [comment]
boot args?

**Comment by VisualEhrmanntraut** [comment]
also we don't speak this language please speak in english

**Comment by 00x0A** [comment]
my rx 6700 xt works fine in sequoia, patched latest nootrx and lilu was needed.

**Comment by Love-Myself-Song** [comment]
> 我的 rx 6700 xt 在红杉中工作正常，需要修补最新的 nootrx 和 lilu。

你的是什么配置 我使用的也是最新版本的驱动

**Comment by VisualEhrmanntraut** [comment]
Failed to receive required information.
