### ISSUE TITLE
Add Navi 33XL Support

### ISSUE THREAD

**Issue by fbrunosf** [ChefKissInc/NootRX#66]
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 7 5800X

### What is your GPU's model?

AMD Radeon RX 7600 (Navi 33 XL)

### Please describe the feature in detail.

I want NootRX to support Navi 33 XL graphics cards.

### What alternatives have you tried, if any?

Nothing.

### Feature request submission terms

- [X] I am using the latest version of NootRX, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootRX makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment]
Magic does not exist.

**Comment by blahdy** [comment]
> Magic does not exist.

What about unicorns?

**Comment by VisualEhrmanntraut** [comment]
neither :-(
