### ISSUE TITLE
Can it support 6800m

### ISSUE THREAD

**Issue by weizhuangzheX** [ChefKissInc/NootRX#7]
Hello author, my laptop graphics card model is 6800m, which is based on the Navi22 core. However, since this laptop does not support direct connection with a standalone display, it can be achieved through Type-C to DP external display. I am not sure if it can support my use of the current version in the future. The following prompt appears

----------------------------------------------------------------------------------------------------
panic(cpu 0 caller 0xffffff802324b301): NootRX   X6000FB: @ Failed to resolve CailAsicCapsTable

Panicked task 0xffffffa00f6289d8: 175 threads: pid 0: kernel_task
Backtrace (CPU 0), panicked thread: 0xffffffa01036e0c8, Frame : Return Address
0xffffffd88e49f670 : 0xffffff801d67207d 
0xffffffd88e49f6c0 : 0xffffff801d7c6164 
0xffffffd88e49f700 : 0xffffff801d7b5c77 
0xffffffd88e49f750 : 0xffffff801d612951 
0xffffffd88e49f770 : 0xffffff801d67235d 
0xffffffd88e49f860 : 0xffffff801d671a07 
0xffffffd88e49f8c0 : 0xffffff801dddb40b 
0xffffffd88e49f9b0 : 0xffffff802324b301 
0xffffffd88e49fc70 : 0xffffff8021572fdd 
0xffffffd88e49fcb0 : 0xffffff802156ae75 
0xffffffd88e49fd00 : 0xffffff801dc737f2 
0xffffffd88e49fd60 : 0xffffff801dc88acd 
0xffffffd88e49fdb0 : 0xffffff801dd0a21e 
0xffffffd88e49fe00 : 0xffffff801dce7417 
0xffffffd88e49fec0 : 0xffffff801dce6d0f 
0xffffffd88e49ff20 : 0xffffff801dce9e9a 
0xffffffd88e49ffa0 : 0xffffff801d61219e 
      Kernel Extensions in backtrace:
         as.vit9696.Lilu(1.6.7)[087C34D2-49F8-3FDA-8757-27E9425C9EE4]@0xffffff8021568000->0xffffff8021593fff
         com.ChefKissInc.NootRX(1.0)[3F77795B-B03A-3C2D-97BD-FD3B1915B145]@0xffffff8023248000->0xffffff802346afff
            dependency: as.vit9696.Lilu(1.6.7)[087C34D2-49F8-3FDA-8757-27E9425C9EE4]@0xffffff8021568000->0xffffff8021593fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1DE0C664-DA38-3436-89ED-1BA79DF0A726]@0xffffff80200ac000->0xffffff80200ddfff

Process name corresponding to current thread (0xffffffa01036e0c8): kernel_task
Boot args: -v alcid=13 -vi2c-force-polling 

Mac OS version:
22G74

Kernel version:
Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Kernel UUID: 8295C77B-2AAB-3471-81B5-438F59B1A36D
roots installed: 0
KernelCache slide: 0x000000001d200000
KernelCache base:  0xffffff801d400000
Kernel slide:      0x000000001d2dc000
Kernel text base:  0xffffff801d4dc000
__HIB  text base: 0xffffff801d300000
System model name: MacBookPro16,3 (Mac-E7203C0F68AA0004)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 20441913707
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000004c2fd2bc8
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000ac6ce591c 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff900d668000 - 0xffffffb00d668000
  . PGZ   : 0xffffff900d668000 - 0xffffff9011669000
  . VM    : 0xffffff9011669000 - 0xffffff94dd99c000
  . RO    : 0xffffff94dd99c000 - 0xffffff9677002000
  . GEN0  : 0xffffff9677002000 - 0xffffff9b43335000
  . GEN1  : 0xffffff9b43335000 - 0xffffffa00f668000
  . GEN2  : 0xffffffa00f668000 - 0xffffffa4db99b000
  . GEN3  : 0xffffffa4db99b000 - 0xffffffa9a7cce000
  . DATA  : 0xffffffa9a7cce000 - 0xffffffb00d668000
  Metadata: 0xffffffb8263f8000 - 0xffffffb8463f8000
  Bitmaps : 0xffffffb8463f8000 - 0xffffffb84c3f8000
  Extra   : 0 - 0

**Comment by ExtremeXT** [comment]
@weizhuangzheX Are you using NootedRed? They conflict, you can't use both NootRX and NootedRed at once. You MIGHT be able to get the dGPU working for external displays if you really want to, or even the internal display if it has a MUX chip (most laptops don't). Support is still not guaranteed on mobile cards.
