### ISSUE TITLE
QuickLook is pausing/freezing system for 5-10 seconds on 6750xt

### ISSUE THREAD

**Issue by blodt** [ChefKissInc/NootRX#70]
### macOS Version

Ventura

### What is your CPU's model?

Intel i7 8700

### What is your GPU's model?

PowerColor RX 6750XT

### Please describe the behaviour in detail.

When opening QuickLook on images, usually about the 3rd or 4th image it will freeze while animating the open of the QL window and the whole system will hang for 3-8 seconds or so and then recover and proceed on.

Does it consistently - not solved by clean reboot or anything else.

I don't have the Intel iGPU enabled.  Perhaps I should and that would handle QuickLook things and eliminate problems here?

### What should've happened instead?

Quick Look shouldn't freeze

**Comment by blodt** [comment]
Appreciate the auto-reply -- Shouldn't be related to any of the listed issues.  This install was working 100% with no QuickLook hangs on a 6600XT before swapping in the 6750XT -- only change made was removing WhateverGreen, placing latest NootRX in and updating config.plist

One thing I can think of might be that I'm not using iGPU (totally disabled) -- but I do have one with my i7 8700

Would it be better to have the iGPU enabled in headless mode here perhaps?

**Comment by wander555** [comment]
same as my 6750xt,not in quick look,but also in browsers,hope the  update will fix this.

**Comment by matteosusca** [comment]
could be an issue with the 6750XT. I have the same problem with my 6750XT, especially when browsing, watching streaming content, and during graphics-demanding activities like gaming. Sometimes, after the freeze, random red or yellow artifacts appear. I'm also still able to move the cursor during the freeze and hear what I was watching, but I can't interact with anything

**Comment by VisualEhrmanntraut** [comment]
Probably just #17

**Comment by matteosusca** [comment]
> Probably just #17

I don't think so. Before the freeze, there are no artifacts, and even when it freezes, most of the time it doesn't show any artifacts. The symptoms are very similar to those described by OP: a system freeze for about 3-8 seconds. I can't interact with the active window, the top bar, or the dock. I can only move the mouse.
I'm on Sonoma

**Comment by ivanocj** [comment]
> > Probably just #17
> 
> I don't think so. Before the freeze, there are no artifacts, and even when it freezes, most of the time it doesn't show any artifacts. The symptoms are very similar to those described by OP: a system freeze for about 3-8 seconds. I can't interact with the active window, the top bar, or the dock. I can only move the mouse. I'm on Sonoma

The exact same scenario is happening with my 6750xt under Ventura. 😟

**Comment by VisualEhrmanntraut** [comment]
Merging with #17. Please make sure to also retry with the latest commit.
