### ISSUE TITLE
Lower Geekbench score Than Older version

### ISSUE THREAD

**Issue by colorzpe** [ChefKissInc/NootRX#71]
### macOS Version

Monterey

### What is your CPU's model?

8700k

### What is your GPU's model?

6700xt Ref

### Please describe the behaviour in detail.

Geekbench score (opencl,metal) lower than nootrx older version
and lower than 6600xt

### What should've happened instead?

Same score or a bit lower or better

**Comment by VisualEhrmanntraut** [comment]
The workflow policy was changed because on some GPUs it was causing coil whine.

**Comment by kadaxo** [comment]
> The workflow policy was changed because on some GPUs it was causing coil whine.

Coil whine is normal for RX 6000 series. Talking about my GPU on Windows on high load it also whines. So why cut the performance?

**Comment by VisualEhrmanntraut** [comment]
Well I didn't know that. I'm a Mac user, I have an M3 MacBook Pro. 😆

**Comment by kadaxo** [comment]
I made some tests with Cinebench, and Cinebench score is normal.

**Comment by VisualEhrmanntraut** [comment]
Well, I still think the reason it's lower is not because it's wrong but because it was being boosted due macOS' value of COMPUTE_WORKLOAD

**Comment by VisualEhrmanntraut** [comment]
[NootRX-1.0.0-DEBUG.zip](https://github.com/user-attachments/files/16769033/NootRX-1.0.0-DEBUG.zip)
[NootRX-1.0.0-RELEASE.zip](https://github.com/user-attachments/files/16769046/NootRX-1.0.0-RELEASE.zip)


is this build ok

**Comment by kadaxo** [comment]
> [NootRX-1.0.0-DEBUG.zip](https://github.com/user-attachments/files/16769033/NootRX-1.0.0-DEBUG.zip) [NootRX-1.0.0-RELEASE.zip](https://github.com/user-attachments/files/16769046/NootRX-1.0.0-RELEASE.zip)
> 
> is this build ok

Nope. Same metal score. I get 60k+ more metal score with [[bfff2a8]](https://github.com/ChefKissInc/NootRX/commit/bfff2a83394619d71a7c8c51f3e3c97e2165d492) commit btw.

**Comment by VisualEhrmanntraut** [comment]
The previous high scores were a mistake, it was using Compute workload, but macOS uses VR workload. The compute workload will suck out too much power and cause coil whine on some of the GPUs.

**Comment by VisualEhrmanntraut** [comment]
The current changes use the default workload. These builds use the correct workload.

**Comment by VisualEhrmanntraut** [comment]
(You should also make sure to use the "Shaneee" PAT patch and not the "algrey" one for better performance if you are on an AMD CPU)

**Comment by VisualEhrmanntraut** [comment]
@00x0A I remember you had coil whine, can you try the builds in https://github.com/ChefKissInc/NootRX/issues/71#issuecomment-2313540776 and tell me if they have coil whine?

**Comment by VisualEhrmanntraut** [comment]
Merging with #69 as I theorise this is the primary cause now.

**Comment by colorzpe** [comment]
Sorry for the late response 
if new version is correct workload and score
seem like performance worse than native support 6600xt even Vega 56
![Screen Shot 2567-11-09 at 01 34 27](https://github.com/user-attachments/assets/1702d812-d25a-45e1-beb9-f6b16c30f4bf)


and this is the version I was referring to previously (normal score)
[NootRX.kext.zip](https://github.com/user-attachments/files/17682746/NootRX.kext.zip)

**Comment by colorzpe** [comment]
Update I'm testing with Cinebench 2024 ,Heaven Benchmark
Heaven Bench Score Same
![Screen Shot 2567-11-09 at 02 08 45](https://github.com/user-attachments/assets/176d26af-bbc2-44a6-b5f0-53613ee73ced)
But Cinebench not

**Comment by VisualEhrmanntraut** [comment]
> Merging with #69 as I theorise this is the primary cause now.

.

**Comment by VisualEhrmanntraut** [comment]
turns out it wasn't that. However, the issue should be resolved now
