### ISSUE TITLE
system freeze while i was using jetbrians idea

### ISSUE THREAD

**Issue by zakariyya215** [ChefKissInc/NootRX#72]
### macOS Version

Monterey

### What is your CPU's model?

AMD Ryzen5 5600G

### What is your GPU's model?

Peladn RX6750XT

### Please describe the behaviour in detail.

It stucks for like 7-15 secs randomly while I was using IDEA,especially compiling java projects, here's the console msg
![Uploading 截屏2024-08-06 16.17.10.png…]()

### What should've happened instead?

.

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

[归档.zip](https://github.com/user-attachments/files/16507496/default.zip)

**Comment by zakariyya215** [comment]
[WindowServer-2024-08-18-103201.ips.zip](https://github.com/user-attachments/files/16647036/WindowServer-2024-08-18-103201.ips.zip)
new dumpfile get

**Comment by VisualEhrmanntraut** [comment]
Probably just #17

**Comment by VisualEhrmanntraut** [comment]
Merging with #17. Please make sure to also retry with the latest commit.
