### ISSUE TITLE
The latest commit is not working

### ISSUE THREAD

**Issue by Win10Q** [ChefKissInc/NootRX#73]
### macOS Version

Sonoma

### What is your CPU's model?

AMD RYZEN 5800X

### What is your GPU's model?

AMD RADEN 6700XT

### Please describe the behaviour in detail.

I updated the latest version of nootrx and the video memory has changed to 14M
![QQ图片20240813183953](https://github.com/user-attachments/assets/b8acb6f9-b328-4d87-83c7-72c1e2a86d5e)

### What should've happened instead?

The old version of the kext is no problem

**Comment by Win10Q** [comment]
I updated to 14.6.1 and still can't drive properly

**Comment by Win10Q** [comment]
Understand, understand, thank you for the kext you developed

**Comment by VisualEhrmanntraut** [comment]
Please let me know if it works correctly once it builds.
