### ISSUE TITLE
6750GRE 12g Sequoia support

### ISSUE THREAD

**Issue by julian-win** [ChefKissInc/NootRX#76]
### macOS Version

Sequoia

### What is your CPU's model?

13600k

### What is your GPU's model?

AMD 6750GRE 12g

### Please describe the behaviour in detail.

Loaded latest LiluV1.6.8 and NootRX , failed to enter system when NootRX loaded

### What should've happened instead?

Does NootRX already support Sequoia?

**Comment by EAZYBLACK** [comment]
NootRX already supports sequoia yes
