### ISSUE TITLE
MacOS Sonoma on Laptop MSI Ryzen 5800H & AMD RX 6600M 8GB

### ISSUE THREAD

**Issue by Updats** [ChefKissInc/NootRX#81]
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 5800H

### What is your GPU's model?

AMD RADEON RX 6600M 8GB

### Please describe the feature in detail.

I was unable to activate my RX 6600M using nootRX, so do I need to do something specific on my laptop? my laptop doesn't have mux switch support.

### What alternatives have you tried, if any?

I tried with WhateverGreen, NootRX, I used `device properticies` but it doesn't work, what should I do?
- I only got the AMD iGPU.

**Comment by alvindimas05** [comment]
Sir, I already answered your question at AMD OSX Discord. If you don't have Mux Switch, you can try connect into external monitor but you need to disable internal monitor.
