### ISSUE TITLE
The AMD 6750GRE 10G cannot be properly driven.

### ISSUE THREAD

**Issue by 646877865** [ChefKissInc/NootRX#84]
### macOS Version

Sonoma

### What is your CPU's model?

AMD R5 5600

### What is your GPU's model?

AMD 6750GRE 10G

### Please describe the behaviour in detail.

When installing the system, the screen shows snowflakes, the screen goes blank, and the mouse can still move.

### What should've happened instead?

The graphics card is properly driven.

**Comment by VisualEhrmanntraut** [comment]
I don't understand what you're talking about.

**Comment by VisualEhrmanntraut** [comment]
Failed to respond with more elaborate issue description (pictures, etc). Closing. Make sure to retry with latest commit.
