### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by noahbroyles** [ChefKissInc/NootRX#9]
This may just be a me problem, but I can't figure out how to build/compile this project for use. 
I don't see anything available for download under the Releases for this repo either.

How can I build/use this project?

I tried following the build commands in the [GitHub workflow](https://github.com/ChefKissInc/NootRX/blob/master/.github/workflows/main.yml) but kept getting these errors:

```console
/Users/noah/Downloads/HACKINTOSH/NootRX/Lilu.kext/Contents/Resources/Headers/kern_util.hpp:14:10: fatal error: 'libkern/libkern.h' file not found
#include <libkern/libkern.h>
         ^~~~~~~~~~~~~~~~~~~
```
I'm on an M1 Pro MBP running macOS 14.1 (23B74)

**Comment by cornshiba** [comment]
Go to the actions tab, select "Cl" as the workflow, and download the latest commit.

**Comment by noahbroyles** [comment]
@cornshiba Thanks a lot! This would be helpful to add to the README or Releases section of this repo

**Comment by 21307369** [comment]
Why not just provide the built file?
