### ISSUE TITLE
Apple Music does not stream audio over Bluetooth

### ISSUE THREAD

**Issue by actuallyaridan** [ChefKissInc/NootRX#90]
### macOS Version

Sequoia

### What is your CPU's model?

AMD Ryzen 5 3600

### What is your GPU's model?

AMD Radeon RX 6700 XT

### Please describe the behaviour in detail.

Apple Music does not stream over Bluetooth (tested with Fenvi T919), even with Lossless and Dolby Atmos disabled. Streams fine over speakers and display-audio, but not Bluetooth audio.  

Other people have had the exact same issue (on unknown cards) and mentioned DRM to be the culprit and that they had to switch to a supported GPU to resolve it: https://www.reddit.com/r/hackintosh/comments/1am27te/comment/lejr9i6/

### What should've happened instead?

Apple Music should be streaming over Bluetooth. Could potentially need better DRM support to resolve the issue.

**Comment by VisualEhrmanntraut** [comment]
#4

**Comment by VisualEhrmanntraut** [comment]
Same underlying problem.

**Comment by actuallyaridan** [comment]
Alright!

Do you guys think it's fixable? Because other than that, this kext is more or less perfect.

**Comment by VisualEhrmanntraut** [comment]
I don't have any idea yet on this issue, in theory the patches that exist right now should've worked for all of the DRM code, not just parts of it.
