### ISSUE TITLE
Instalation guide

### ISSUE THREAD

**Issue by larini** [ChefKissInc/NootRX#91]
### macOS Version

Sequoia

### What is your CPU's model?

AMD Ryzen 3700x

### What is your GPU's model?

AMD Radeon RX 6950 XT

### Please describe the feature in detail.

Can't get this to work in my system. How exactly I have to install this kext? Should I remove WhereverGreen or keep, or what? Thanks.

### What alternatives have you tried, if any?

Look some webpages with loose information.

**Comment by VisualEhrmanntraut** [comment]
https://chefkissinc.github.io/applehax/nootrx/
