### ISSUE TITLE
many programs stuck after wake

### ISSUE THREAD

**Issue by mongomama** [ChefKissInc/NootRX#94]
### macOS Version

Sequoia

### What is your CPU's model?

10700K

### What is your GPU's model?

6750gre

### Please describe the behaviour in detail.

boot normally and behaves right，but after awake from sleep，it causes many programs stopping responding，including Music，App Store，hackintool，etc. MacOS isn't stucking though. the program Preview，it can open PNG files normally，but stuck with jpeg file

### What should've happened instead?

those programs should be running normally,maybe sth wrong with  Metal API？

**Comment by VisualEhrmanntraut** [comment]
Hm, does it happen if you disable VCN using `-NRXNoVCN` in boot args?

**Comment by mongomama** [comment]
> Hm, does it happen if you disable VCN using `-NRXNoVCN` in boot args?

Just tried this，bug remains, OCAT runs normally though.

**Comment by mongomama** [comment]
> Hm, does it happen if you disable VCN using `-NRXNoVCN` in boot args?

think I found sth,the intel igpu uhd630,it relies on Whatevergreen,since I now don't have whatevergreen running,everytime any program calls for iGPU will leads to a panic... 
<img width="393" alt="image" src="https://github.com/user-attachments/assets/c37418b2-9660-4444-ae61-b09692b666a1">
i'm not a programmer and my English is not good,sorry if...U know...

**Comment by VisualEhrmanntraut** [comment]
Ah, interesting, thanks for the information. I plan to merge NootRX with NootedRed, and maybe also add Intel support to NootedRed, so I guess if and when that happens that would be fixed I guess.

**Comment by mongomama** [comment]
> Ah, interesting, thanks for the information. I plan to merge NootRX with NootedRed, and maybe also add Intel support to NootedRed, so I guess if and when that happens that would be fixed I guess.

Glad about your plan,so I disabled iGPU in my bios,now OS and programs runs alright at least. Looking forward to your iteration,many thanks to your hard work.
