### ISSUE TITLE
Geekbench low score

### ISSUE THREAD

**Issue by Niko-ske** [ChefKissInc/NootRX#99]
### macOS Version

Sequoia

### What is your CPU's model?

i5-12600KF

### What is your GPU's model?

AMD RX6750GRE 12G

### Please describe the feature in detail.

Hello, I want to feedback a question, mainly reflected in the running points of GeekBench6, whether it is Metal or OpenCL running points lower than RX6700XT a lot.RX6700XT ,metal 160000+,mine 80000+.I know this abnormal![Image](https://github.com/user-attachments/assets/c6515dcd-a48e-4173-af97-5d6ed9a0be7a)
![Image](https://github.com/user-attachments/assets/e5ba2a9e-7762-4303-be3e-17901a8bcbd6)
  

### What alternatives have you tried, if any?

Hope to be improved in the subsequent version. Thank you!

**Comment by VisualEhrmanntraut** [comment]
the latest version should have that issue fixed though

**Comment by Niko-ske** [comment]
Thank you for your replay and also for your efforts。Wishing everthing all the best！

| |
wylong993
|
|
***@***.***
|
---- Replied Message ----
| From | Visual ***@***.***> |
| Date | 12/02/2024 01:15 |
| To | ChefKissInc/NootRX ***@***.***> |
| Cc | Niko-ske ***@***.***>,
State ***@***.***> |
| Subject | Re: [ChefKissInc/NootRX] Geekbench low score (Issue #99) |

the latest version should have that issue fixed though

**Comment by Niko-ske** [comment]
I use the latest version，but it didn't work out
